[package]
name = "sysintercept"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
ctor = "0.5.0"
lazy_static = "1.5.0"
libc = "0.2.175"
serde_json = "1.0.142"
syscall-intercept = { path = "syscall-intercept-rs" }

[lib]
name = "intercept"
crate-type = ["rlib", "cdylib"]
