[package]
name = "unshell-rs-lib"
edition = "2024"

[dependencies]
base64 = "0.22.1"
crossbeam-channel = "0.5.15"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
