[package]
name = "unshell-rs-lib"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bincode = "2.0.1"
crossbeam-channel = "0.5.15"
log = "0.4.27"
rand = "0.9.1"
uuid = { version = "1.17.0", features = ["v4"] }
